zuul:
# Service will be mapped under the /api URI
 prefix: /api
# Uncomment to disable auto-registering all services read from Eureka
 ignoredServices: '*'
 routes:
  test:
   path: /redirect/**
   url: http://google.com
  formcountry:
   path: /movie/**
   serviceId: Movie
  localcountry:
   path: /cust/**
   serviceId: Cust
